[package]
name = "gussing_game"
version = "0.1.0"
authors = ["jiwon <4dakto@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
